### ISSUE TITLE
Support 16:10 aspect

### ISSUE THREAD

**Issue by WilliamFeely** [shicky256/SonicMania43Patcher#1]
I have a 16:10 monitor.  Could you add an option to support the 16:10 aspect ratio too?

**Comment by shicky256** [comment]
Try setting the width variable to 384 and rebuilding (no idea if this works or if the engine supports that aspect ratio, you can be a pioneer).

**Comment by shicky256** [comment]
[SonicManiaPatcher.zip](https://github.com/shicky256/SonicMania43Patcher/files/1290091/SonicManiaPatcher.zip)
Try this, it should work 
Directions:
1. Make sure Sonic Mania is set to launch windowed
2. Put the patcher executable in the Sonic Mania folder
3. Create a shortcut to it and put it somewhere (don't run the patcher directly from the folder, since it's also called Sonic Mania and it'll try and patch the Explorer window instead).
4. The patcher will patch the game and make it fullscreen.

**Comment by WilliamFeely** [comment]
Looking good:
https://imgur.com/a/gYX6p
